import { describe, it, expect } from 'vitest';
import {
  parseMo2Modlist,
  parseMo2Plugins,
  parseVortexExport,
  compareVersions,
  normalizeModName,
  matchModInInventory,
} from '../src/storage/inventory.js';

describe('Inventory Storage & Parsers', () => {
  describe('normalizeModName & compareVersions', () => {
    it('normalizes mod names for reliable matching', () => {
      expect(normalizeModName('SkyUI_5_2_SE')).toBe('skyui 5 2 se');
      expect(normalizeModName('Unofficial Skyrim Special Edition Patch (USSEP) v4.2.5b')).toBe(
        'unofficial skyrim special edition patch (ussep)'
      );
      expect(normalizeModName('')).toBe('');
    });

    it('correctly compares version numbers and strings', () => {
      expect(compareVersions('1.2.0', '1.1.0')).toBe(1);
      expect(compareVersions('1.0.0', '1.0.0')).toBe(0);
      expect(compareVersions('1.0.5', '1.2.0')).toBe(-1);
      expect(compareVersions('v2.4.1', '2.4.0')).toBe(1);
      expect(compareVersions('5.2SE', '5.2SE')).toBe(0);
    });
  });

  describe('parseMo2Modlist', () => {
    it('parses enabled, disabled, and separator lines from MO2 modlist.txt', () => {
      const sample = `
# This file was automatically generated by Mod Organizer.
*DLC: Dawnguard
*DLC: Dragonborn
+SkyUI_5_2_SE [1234]
+Unofficial Skyrim Special Edition Patch
-Disabled Old Mod - 1.0.2
*--- Core Frameworks ---
+Address Library for SKSE Plugins (5678)
`;
      const result = parseMo2Modlist(sample);
      expect(result.separators).toEqual([
        'DLC: Dawnguard',
        'DLC: Dragonborn',
        '--- Core Frameworks ---',
      ]);
      expect(result.mods.length).toBe(4);

      // SkyUI
      expect(result.mods[0].name).toBe('SkyUI_5_2_SE [1234]');
      expect(result.mods[0].id).toBe(1234);
      expect(result.mods[0].enabled).toBe(true);

      // USSEP
      expect(result.mods[1].enabled).toBe(true);

      // Disabled mod
      expect(result.mods[2].enabled).toBe(false);
      expect(result.mods[2].version).toBe('1.0.2');

      // Address Library
      expect(result.mods[3].id).toBe(5678);
      expect(result.mods[3].enabled).toBe(true);
    });
  });

  describe('parseMo2Plugins', () => {
    it('parses active and inactive plugins from load order', () => {
      const sample = `
# This file was automatically generated by Mod Organizer.
*Skyrim.esm
*Update.esm
*SkyUI_SE.esp
Unofficial Skyrim Special Edition Patch.esp
*Alternate Start - Live Another Life.esp
`;
      const result = parseMo2Plugins(sample);
      expect(result.plugins.length).toBe(5);
      expect(result.activeCount).toBe(4);
      expect(result.plugins[2].active).toBe(true);
      expect(result.plugins[3].active).toBe(false);
    });
  });

  describe('parseVortexExport', () => {
    it('parses Vortex JSON state exports', () => {
      const sample = {
        mods: [
          { name: 'SkyUI', modId: 1234, version: '5.2', state: 'installed' },
          { name: 'USSEP', modId: '266', version: '4.2.5', state: 'disabled' },
        ],
      };
      const result = parseVortexExport(sample);
      expect(result.mods.length).toBe(2);
      expect(result.mods[0].id).toBe(1234);
      expect(result.mods[0].enabled).toBe(true);
      expect(result.mods[1].enabled).toBe(false);
    });
  });

  describe('matchModInInventory', () => {
    const inventory = {
      games: {
        skyrimspecialedition: {
          mods: {
            '1234': {
              id: 1234,
              name: 'SkyUI',
              normalizedName: 'skyui',
              version: '5.2',
              enabled: true,
            },
            '266': {
              id: 266,
              name: 'Unofficial Skyrim Special Edition Patch',
              normalizedName: 'unofficial skyrim special edition patch',
              version: '4.2.0',
              enabled: true,
            },
          },
        },
      },
    };

    it('matches mod by Mod ID with update available flag', () => {
      const match1 = matchModInInventory(
        inventory,
        'skyrimspecialedition',
        '1234',
        'SkyUI',
        '5.2'
      );
      expect(match1.isInstalled).toBe(true);
      expect(match1.updateAvailable).toBe(false);

      const match2 = matchModInInventory(
        inventory,
        'skyrimspecialedition',
        '266',
        'USSEP',
        '4.3.0'
      );
      expect(match2.isInstalled).toBe(true);
      expect(match2.updateAvailable).toBe(true);
    });

    it('fuzzy matches mod by normalized name when Mod ID is missing', () => {
      const match = matchModInInventory(
        inventory,
        'skyrimspecialedition',
        null,
        'SkyUI SE',
        '5.2'
      );
      expect(match.isInstalled).toBe(true);
    });

    it('returns not installed for unknown mod', () => {
      const match = matchModInInventory(
        inventory,
        'skyrimspecialedition',
        '99999',
        'Unknown Mod'
      );
      expect(match.isInstalled).toBe(false);
    });
  });
});
