export const LOG_PREFIX = '[NXDT]';

export const STORAGE_KEY_STATS = 'stats';
export const STORAGE_KEY_COLLECTION_HISTORY = 'collection_history';
export const NEXUS_HOSTS = ['nexusmods.com'];
export const CDN_HOSTS = ['nexus-cdn.com'];

export const URL_SCHEME_HTTPS = 'https:';

export const DOWNLOAD_METHOD_VORTEX = 0;
export const DOWNLOAD_METHOD_BROWSER = 1;

export const MESSAGE_TYPES = {
  PING: 'NXDT_PING',
  FOCUS_COLLECTION_PANEL: 'NXDT_FOCUS_COLLECTION_PANEL',
  FETCH_COLLECTION_REVISIONS: 'NXDT_FETCH_COLLECTION_REVISIONS',
  FETCH_COLLECTION_MODS: 'NXDT_FETCH_COLLECTION_MODS',
  GET_COLLECTION_HISTORY: 'NXDT_GET_COLLECTION_HISTORY',
  SET_COLLECTION_HISTORY: 'NXDT_SET_COLLECTION_HISTORY',
  START_DOWNLOAD: 'NXDT_START_DOWNLOAD',
  RESOLVE_COLLECTION_DOWNLOAD: 'NXDT_RESOLVE_COLLECTION_DOWNLOAD',
  RESOLVE_ARCHIVED_DOWNLOAD: 'NXDT_RESOLVE_ARCHIVED_DOWNLOAD',
  RESOLVE_MOD_DOWNLOAD: 'NXDT_RESOLVE_MOD_DOWNLOAD',
  COLLECTION_FINISHED: 'NXDT_COLLECTION_FINISHED',
};


export const LOG_LEVELS = {
  DEBUG: 10,
  INFO: 20,
  WARN: 30,
  ERROR: 40,
};
